// <auto-generated />
using System;
using CW2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CW2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230731181549_addWorkout")]
    partial class addWorkout
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CW2.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheatMeal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeightValue")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkoutDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkoutDuration")
                        .HasColumnType("int");

                    b.Property<string>("WorkoutType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheatMeal = "Snack",
                            WeightValue = 70,
                            WorkoutDate = new DateTime(2023, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkoutDuration = 40,
                            WorkoutType = "Legs"
                        },
                        new
                        {
                            Id = 2,
                            CheatMeal = "Rolls",
                            WeightValue = 72,
                            WorkoutDate = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkoutDuration = 30,
                            WorkoutType = "Shoulders"
                        },
                        new
                        {
                            Id = 3,
                            CheatMeal = "Pizza",
                            WeightValue = 80,
                            WorkoutDate = new DateTime(2023, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkoutDuration = 45,
                            WorkoutType = "Chest"
                        },
                        new
                        {
                            Id = 4,
                            CheatMeal = "Burger",
                            WeightValue = 85,
                            WorkoutDate = new DateTime(2023, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkoutDuration = 35,
                            WorkoutType = "Back"
                        },
                        new
                        {
                            Id = 5,
                            CheatMeal = "Ice Cream",
                            WeightValue = 68,
                            WorkoutDate = new DateTime(2023, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkoutDuration = 30,
                            WorkoutType = "Arms"
                        },
                        new
                        {
                            Id = 6,
                            CheatMeal = "Fries",
                            WeightValue = 75,
                            WorkoutDate = new DateTime(2023, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkoutDuration = 50,
                            WorkoutType = "Legs"
                        },
                        new
                        {
                            Id = 7,
                            CheatMeal = "Cake",
                            WeightValue = 70,
                            WorkoutDate = new DateTime(2023, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkoutDuration = 30,
                            WorkoutType = "Shoulders"
                        },
                        new
                        {
                            Id = 8,
                            CheatMeal = "Donuts",
                            WeightValue = 78,
                            WorkoutDate = new DateTime(2023, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkoutDuration = 45,
                            WorkoutType = "Chest"
                        },
                        new
                        {
                            Id = 9,
                            CheatMeal = "Chips",
                            WeightValue = 83,
                            WorkoutDate = new DateTime(2023, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkoutDuration = 50,
                            WorkoutType = "Back"
                        },
                        new
                        {
                            Id = 10,
                            CheatMeal = "Cookies",
                            WeightValue = 66,
                            WorkoutDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkoutDuration = 35,
                            WorkoutType = "Arms"
                        },
                        new
                        {
                            Id = 11,
                            CheatMeal = "Chocolate",
                            WeightValue = 72,
                            WorkoutDate = new DateTime(2023, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkoutDuration = 40,
                            WorkoutType = "Legs"
                        },
                        new
                        {
                            Id = 12,
                            CheatMeal = "Popcorn",
                            WeightValue = 69,
                            WorkoutDate = new DateTime(2023, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkoutDuration = 30,
                            WorkoutType = "Shoulders"
                        },
                        new
                        {
                            Id = 13,
                            CheatMeal = "Pasta",
                            WeightValue = 79,
                            WorkoutDate = new DateTime(2023, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkoutDuration = 45,
                            WorkoutType = "Chest"
                        },
                        new
                        {
                            Id = 14,
                            CheatMeal = "Nachos",
                            WeightValue = 82,
                            WorkoutDate = new DateTime(2023, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkoutDuration = 25,
                            WorkoutType = "Back"
                        },
                        new
                        {
                            Id = 15,
                            CheatMeal = "Soda",
                            WeightValue = 65,
                            WorkoutDate = new DateTime(2023, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkoutDuration = 35,
                            WorkoutType = "Arms"
                        },
                        new
                        {
                            Id = 16,
                            CheatMeal = "Cheese",
                            WeightValue = 73,
                            WorkoutDate = new DateTime(2023, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkoutDuration = 40,
                            WorkoutType = "Legs"
                        },
                        new
                        {
                            Id = 17,
                            CheatMeal = "Noodles",
                            WeightValue = 68,
                            WorkoutDate = new DateTime(2023, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkoutDuration = 30,
                            WorkoutType = "Shoulders"
                        },
                        new
                        {
                            Id = 18,
                            CheatMeal = "Waffles",
                            WeightValue = 77,
                            WorkoutDate = new DateTime(2023, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkoutDuration = 45,
                            WorkoutType = "Chest"
                        },
                        new
                        {
                            Id = 19,
                            CheatMeal = "Pancakes",
                            WeightValue = 81,
                            WorkoutDate = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkoutDuration = 25,
                            WorkoutType = "Back"
                        },
                        new
                        {
                            Id = 20,
                            CheatMeal = "Sushi",
                            WeightValue = 67,
                            WorkoutDate = new DateTime(2023, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkoutDuration = 35,
                            WorkoutType = "Arms"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
